repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    # Git style
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-vcs-permalinks
    - id: forbid-new-submodules
    - id: no-commit-to-branch

    # Common errors
    - id: end-of-file-fixer
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-yaml
      exclude: ^prerequisites/
    - id: check-merge-conflict
    - id: check-executables-have-shebangs

    # Cross platform
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]

    # Security
    - id: detect-aws-credentials
      args: ['--allow-missing-credentials']
    - id: detect-private-key

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
    - id: shfmt
      args: ['-l', '-i', '2', '-ci', '-sr', '-w']
    - id: shellcheck

# Dockerfile linter
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
    - id: hadolint
      args: [
        '--ignore', 'DL3027', # Do not use apt
        '--ignore', 'DL3007', # Using latest
        '--ignore', 'DL4006', # Not related to alpine
        '--ignore', 'SC1091', # Useless check
        '--ignore', 'SC2015', # Useless check
        '--ignore', 'SC3037', # Not related to alpine
        '--ignore', 'DL3013', # Pin versions in pip
        '--ignore', 'DL3032', # Don't use `yum clean all` missing after yum command.
        '--ignore', 'DL3033', # Don't use Specify version with `yum install -y <package>-<version>`
        '--ignore', 'DL3003', # Don't use Use WORKDIR to switch to a directory
        '--ignore', 'DL3045', # Don't use `COPY` to a relative destination without `WORKDIR` set
        '--ignore', 'SC2035', # Don't use Use ./*glob* or -- *glob* so names with dashes won't become options
      ]
