name: Pre-Commit

on:
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get changed files
      id: file_changes
      run: |
        export DIFF=$(git diff --name-only origin/${{ github.base_ref }} ${{ github.sha }})
        echo "Diff between ${{ github.base_ref }} and ${{ github.sha }}"
        echo "::set-output name=files::$( echo "$DIFF" | xargs echo )"

    # Need to success pre-commit fix push
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    # Skip terraform_tflint which interferes to commit pre-commit auto-fixes
    - uses: actions/setup-python@v2
      # with:
      #   python-version: '3.10'

    - name: Install requisites
      run: |
        # Install pre-commit
        pip install pre-commit
        pre-commit install
        pre-commit install-hooks

    # We run them sepoarate because we don't want to run terraform_docs
    - name: Run pre-commit
      run: |
        pre-commit run --all-files
